export interface BlockDeal {
    id: string;
    date: string;
    stockName: string;
    symbol: string;
    dealType: 'BLOCK';
    transactionType: 'PURCHASE' | 'SELL';
    clientName: string;
    quantity: number;
    tradedPrice: number;
    dealValue: number;
    percentTraded: number;
    exchange: 'BSE' | 'NSE';
}

export const blockDealsData: BlockDeal[] = [
    {
        id: '1',
        date: '31 Dec, 2025',
        stockName: 'Swan Corp',
        symbol: 'SWANCORP',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Jainam Broking Limited',
        quantity: 1500000,
        tradedPrice: 468,
        dealValue: 70.20,
        percentTraded: 0.48,
        exchange: 'BSE',
    },
    {
        id: '2',
        date: '31 Dec, 2025',
        stockName: 'Swan Corp',
        symbol: 'SWANCORP',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'Jupiter India Fund',
        quantity: 1096642,
        tradedPrice: 468,
        dealValue: 51.32,
        percentTraded: 0.35,
        exchange: 'BSE',
    },
    {
        id: '3',
        date: '31 Dec, 2025',
        stockName: 'Swan Corp',
        symbol: 'SWANCORP',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'The Jupiter Global Fund-jupiter India Select',
        quantity: 403358,
        tradedPrice: 468,
        dealValue: 18.87,
        percentTraded: 0.13,
        exchange: 'BSE',
    },
    {
        id: '4',
        date: '29 Dec, 2025',
        stockName: 'BIRLANU',
        symbol: 'BIRLANU',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'Birla Chandrakant',
        quantity: 2928170,
        tradedPrice: 1517.5,
        dealValue: 444.34,
        percentTraded: 34.76,
        exchange: 'NSE',
    },
    {
        id: '5',
        date: '29 Dec, 2025',
        stockName: 'Honasa Consumer',
        symbol: 'HONASA',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Fireside Ventures Investment Fund I',
        quantity: 1851851,
        tradedPrice: 270,
        dealValue: 49.99,
        percentTraded: 0.55,
        exchange: 'NSE',
    },
    {
        id: '6',
        date: '29 Dec, 2025',
        stockName: 'Honasa Consumer',
        symbol: 'HONASA',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'Varun Alagh',
        quantity: 1851851,
        tradedPrice: 270,
        dealValue: 49.99,
        percentTraded: 0.55,
        exchange: 'NSE',
    },
    {
        id: '7',
        date: '29 Dec, 2025',
        stockName: 'BIRLANU',
        symbol: 'BIRLANU',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Ltd Central India Industries',
        quantity: 1406634,
        tradedPrice: 1517.5,
        dealValue: 213.45,
        percentTraded: 16.70,
        exchange: 'NSE',
    },
    {
        id: '8',
        date: '29 Dec, 2025',
        stockName: 'BIRLANU',
        symbol: 'BIRLANU',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Shekhavati Investments And Traders Limited',
        quantity: 556470,
        tradedPrice: 1517.5,
        dealValue: 84.44,
        percentTraded: 6.61,
        exchange: 'NSE',
    },
    {
        id: '9',
        date: '29 Dec, 2025',
        stockName: 'BIRLANU',
        symbol: 'BIRLANU',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Ltd Ashok Investment Corporat Ion',
        quantity: 361743,
        tradedPrice: 1517.5,
        dealValue: 54.89,
        percentTraded: 4.29,
        exchange: 'NSE',
    },
    {
        id: '10',
        date: '28 Dec, 2025',
        stockName: 'Reliance Industries',
        symbol: 'RELIANCE',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'BlackRock India Fund',
        quantity: 5000000,
        tradedPrice: 2450.75,
        dealValue: 1225.38,
        percentTraded: 0.08,
        exchange: 'NSE',
    },
    {
        id: '11',
        date: '28 Dec, 2025',
        stockName: 'HDFC Bank',
        symbol: 'HDFCBANK',
        dealType: 'BLOCK',
        transactionType: 'SELL',
        clientName: 'Morgan Stanley Asia',
        quantity: 3200000,
        tradedPrice: 1720.80,
        dealValue: 550.66,
        percentTraded: 0.04,
        exchange: 'BSE',
    },
    {
        id: '12',
        date: '27 Dec, 2025',
        stockName: 'Tata Motors',
        symbol: 'TATAMOTORS',
        dealType: 'BLOCK',
        transactionType: 'PURCHASE',
        clientName: 'SBI Mutual Fund',
        quantity: 8500000,
        tradedPrice: 875.50,
        dealValue: 744.18,
        percentTraded: 0.28,
        exchange: 'NSE',
    },
];

export const exchangeOptions = ['All Exchanges', 'BSE', 'NSE'];
export const transactionOptions = ['All Transactions', 'PURCHASE', 'SELL'];
export const sortOptions = ['Date (Newest)', 'Date (Oldest)', 'Deal Value (High)', 'Deal Value (Low)', 'Quantity (High)', 'Quantity (Low)'];
