export interface BulkDeal {
    id: string;
    date: string;
    stockName: string;
    symbol: string;
    dealType: 'BULK';
    transactionType: 'PURCHASE' | 'SELL';
    clientName: string;
    quantity: number;
    tradedPrice: number;
    dealValue: number;
    percentTraded: number;
    exchange: 'BSE' | 'NSE';
}

export const bulkDealsData: BulkDeal[] = [
    {
        id: '1',
        date: '02 Jan, 2026',
        stockName: 'Alstone Text',
        symbol: 'ALSTONE',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'Ishaan Tradefin Llp',
        quantity: 87393945,
        tradedPrice: 0.21,
        dealValue: 1.83,
        percentTraded: 1.39,
        exchange: 'BSE',
    },
    {
        id: '2',
        date: '02 Jan, 2026',
        stockName: 'Alstone Text',
        symbol: 'ALSTONE',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Trans Globe Nks Holdings Limited',
        quantity: 60000000,
        tradedPrice: 0.21,
        dealValue: 1.26,
        percentTraded: 0.96,
        exchange: 'BSE',
    },
    {
        id: '3',
        date: '02 Jan, 2026',
        stockName: 'Alstone Text',
        symbol: 'ALSTONE',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Ishaan Tradefin Llp',
        quantity: 54320451,
        tradedPrice: 0.22,
        dealValue: 1.19,
        percentTraded: 0.91,
        exchange: 'BSE',
    },
    {
        id: '4',
        date: '02 Jan, 2026',
        stockName: 'Alstone Text',
        symbol: 'ALSTONE',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Blue Bell Finance Ltd',
        quantity: 50000000,
        tradedPrice: 0.21,
        dealValue: 1.05,
        percentTraded: 0.80,
        exchange: 'BSE',
    },
    {
        id: '5',
        date: '02 Jan, 2026',
        stockName: 'Filatex Fashion',
        symbol: 'FILATEXFASH',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Achintya Securities Limited',
        quantity: 44496744,
        tradedPrice: 0.33,
        dealValue: 1.46,
        percentTraded: 0.55,
        exchange: 'NSE',
    },
    {
        id: '6',
        date: '02 Jan, 2026',
        stockName: 'Filatex Fashion',
        symbol: 'FILATEXFASH',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'Achintya Securities Limited',
        quantity: 40860911,
        tradedPrice: 0.33,
        dealValue: 1.34,
        percentTraded: 0.51,
        exchange: 'NSE',
    },
    {
        id: '7',
        date: '02 Jan, 2026',
        stockName: 'Remedium Lifeca',
        symbol: 'REMEDIUM',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Kamal Asnani',
        quantity: 15000000,
        tradedPrice: 0.7,
        dealValue: 1.05,
        percentTraded: 1.70,
        exchange: 'BSE',
    },
    {
        id: '8',
        date: '02 Jan, 2026',
        stockName: 'Avance Tech',
        symbol: 'AVANCE',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'Alia Commosales Llp',
        quantity: 12221473,
        tradedPrice: 2.07,
        dealValue: 2.52,
        percentTraded: 0.62,
        exchange: 'BSE',
    },
    {
        id: '9',
        date: '02 Jan, 2026',
        stockName: 'Remedium Lifeca',
        symbol: 'REMEDIUM',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'L7 Hitech Private Limited',
        quantity: 10000000,
        tradedPrice: 0.7,
        dealValue: 0.70,
        percentTraded: 1.13,
        exchange: 'BSE',
    },
    {
        id: '10',
        date: '03 Jan, 2026',
        stockName: 'Tata Tech',
        symbol: 'TATATECH',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'Goldman Sachs India Securities',
        quantity: 25000000,
        tradedPrice: 1250.50,
        dealValue: 312.63,
        percentTraded: 0.45,
        exchange: 'NSE',
    },
    {
        id: '11',
        date: '03 Jan, 2026',
        stockName: 'Infosys',
        symbol: 'INFY',
        dealType: 'BULK',
        transactionType: 'SELL',
        clientName: 'Morgan Stanley Asia',
        quantity: 18500000,
        tradedPrice: 1850.25,
        dealValue: 3422.96,
        percentTraded: 0.35,
        exchange: 'NSE',
    },
    {
        id: '12',
        date: '03 Jan, 2026',
        stockName: 'JSW Steel',
        symbol: 'JSWSTEEL',
        dealType: 'BULK',
        transactionType: 'PURCHASE',
        clientName: 'ICICI Prudential Fund',
        quantity: 32000000,
        tradedPrice: 890.75,
        dealValue: 2850.40,
        percentTraded: 0.55,
        exchange: 'BSE',
    },
];

export const exchangeOptions = ['All Exchanges', 'BSE', 'NSE'];
export const transactionOptions = ['All Transactions', 'PURCHASE', 'SELL'];
export const sortOptions = ['Date (Newest)', 'Date (Oldest)', 'Deal Value (High)', 'Deal Value (Low)', 'Quantity (High)', 'Quantity (Low)'];
